table Nexusgoods_order_payments_dataset
	lineageTag: e8904006-2735-4693-9b5a-aeeae49ba5a5

	column order_id
		dataType: string
		lineageTag: 758cc17d-5c12-43a4-9930-32689e28e107
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column payment_sequential
		dataType: int64
		formatString: 0
		lineageTag: 4778f15b-5339-4b64-a60e-1db551e8896d
		summarizeBy: sum
		sourceColumn: payment_sequential

		annotation SummarizationSetBy = Automatic

	column payment_type
		dataType: string
		lineageTag: f9b1dc4b-af31-4ed1-b8c1-6f59cb6b752d
		summarizeBy: none
		sourceColumn: payment_type

		annotation SummarizationSetBy = Automatic

	column payment_installments
		dataType: int64
		formatString: 0
		lineageTag: 8c00fb94-43df-4f2c-986d-2e976ca9d2af
		summarizeBy: sum
		sourceColumn: payment_installments

		annotation SummarizationSetBy = Automatic

	column payment_value
		dataType: double
		lineageTag: aae352ba-c90d-4477-bbd8-afa7edfb533e
		summarizeBy: sum
		sourceColumn: payment_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Nexusgoods_order_payments_dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Irfan\Desktop\Shahida\Nexusgoods store capstone\Nexusgoods_order_payments_dataset.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_id", type text}, {"payment_sequential", Int64.Type}, {"payment_type", type text}, {"payment_installments", Int64.Type}, {"payment_value", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

