table Nexusgoods_customers_dataset
	lineageTag: d373abbc-a46d-4351-ab25-280f789613f1

	column customer_id
		dataType: string
		lineageTag: f55ec97e-c5ec-4922-97a9-991170b63fa9
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: b6982eab-5094-4a0e-820b-87f23aefc7e8
		summarizeBy: sum
		sourceColumn: customer_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 45410e82-9fca-4f84-a3af-a662de09fe62
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: 268dbc99-26d8-4c83-8dec-12fbe9a64c57
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	partition Nexusgoods_customers_dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Irfan\Desktop\Shahida\Nexusgoods store capstone\Nexusgoods_customers_dataset .csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", type text}, {"customer_zip_code_prefix", Int64.Type}, {"customer_city", type text}, {"customer_state", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

